fos_comment:
  db_driver: orm
  class:
    model:
      comment: App\Entity\bundles\FOSCommentBundle\Comment
      thread: App\Entity\bundles\FOSCommentBundle\Thread

assetic:
  bundles: [ "FOSCommentBundle" ]